### ISSUE TITLE
Registration form issues

### ISSUE THREAD

**Issue by sakshamsaxena** [IEEEDTU/Troika-2016#4]
@oasis9594 
Okay so broadly there are 3 issues.
1) You've defined the function, but you haven't called it anywhere. I just did that [here](https://github.com/IEEEDTU/Troika-2016/blob/master/register/index.html#L8)

2) The "select at least 1 event" alert would then probably always popup on body load. This part should be written separately, and run on submit.

3) Notice that it is 'getElementsByName' and 'getElementsByClassName'. Elements, plural. So this always return an array. So use (...)[0] to select the first element, etc. Thus, to actually get the value of selected option, read [this answer](http://stackoverflow.com/questions/1085801/get-selected-value-in-dropdown-list-using-javascript/8549358#8549358). There's no need to individually check each and every field like you did. Instead, just set their CSS property 'display' to 'none', and set all fields to required. That will reduce the js part significantly.

**Comment by sakshamsaxena** [comment]
Try kar itna. Implement karne ke baad koi problem aaye to bataio.

**Comment by oasis9594** [comment]
Sir, I have called the function onsubmit...so all the checking is taking place after clicking the submit button..
